name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./pointerservice/pom.xml
          mvn clean package -f ./paymentservice/pom.xml
          mvn clean package -f ./historyservice/pom.xml
          mvn clean package -f ./webtoonmanagementservice/pom.xml
          mvn clean package -f ./purchaseservice/pom.xml

      - name: Docker Build and push for Pointerservice
        uses: docker/build-push-action@v4
        with:
          context: ./pointerservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pointerservice:latest
            ghcr.io/${{ github.repository }}/pointerservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Paymentservice
        uses: docker/build-push-action@v4
        with:
          context: ./paymentservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/paymentservice:latest
            ghcr.io/${{ github.repository }}/paymentservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Historyservice
        uses: docker/build-push-action@v4
        with:
          context: ./historyservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/historyservice:latest
            ghcr.io/${{ github.repository }}/historyservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Webtoonmanagementservice
        uses: docker/build-push-action@v4
        with:
          context: ./webtoonmanagementservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/webtoonmanagementservice:latest
            ghcr.io/${{ github.repository }}/webtoonmanagementservice:${{ github.ref_name }}
            
      - name: Docker Build and push for Purchaseservice
        uses: docker/build-push-action@v4
        with:
          context: ./purchaseservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/purchaseservice:latest
            ghcr.io/${{ github.repository }}/purchaseservice:${{ github.ref_name }}
            
