server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: pointerservice
          uri: http://localhost:8082
          predicates:
            - Path=/pointers/**, 
        - id: paymentservice
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**, 
        - id: historyservice
          uri: http://localhost:8084
          predicates:
            - Path=/histories/**, 
        - id: webtoonmanagementservice
          uri: http://localhost:8085
          predicates:
            - Path=/webtoons/**, 
        - id: purchaseservice
          uri: http://localhost:8086
          predicates:
            - Path=/purchases/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pointerservice
          uri: http://pointerservice:8080
          predicates:
            - Path=/pointers/**, 
        - id: paymentservice
          uri: http://paymentservice:8080
          predicates:
            - Path=/payments/**, 
        - id: historyservice
          uri: http://historyservice:8080
          predicates:
            - Path=/histories/**, 
        - id: webtoonmanagementservice
          uri: http://webtoonmanagementservice:8080
          predicates:
            - Path=/webtoons/**, 
        - id: purchaseservice
          uri: http://purchaseservice:8080
          predicates:
            - Path=/purchases/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
