apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtoonmanagementservice
  labels:
    app: webtoonmanagementservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtoonmanagementservice
  template:
    metadata:
      labels:
        app: webtoonmanagementservice
    spec:
      containers:
        - name: webtoonmanagementservice
          image: "username/webtoonmanagementservice:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
