apiVersion: v1
kind: Service
metadata:
  name: webtoonmanagementservice
  labels:
    app: webtoonmanagementservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: webtoonmanagementservice