apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchaseservice
  labels:
    app: purchaseservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchaseservice
  template:
    metadata:
      labels:
        app: purchaseservice
    spec:
      containers:
        - name: purchaseservice
          image: "username/purchaseservice:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
